import type { Metadata } from "next";
import { 
  // Geist, Geist_Mono 
  Epilogue
} from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layouts/sidebar";
import Header from "@/components/layouts/header";

const epilogue = Epilogue({
  subsets: ["latin"],
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={epilogue.className}
      >
        <main>
          <div className="border-t">
            <div className="bg-background">
              <div className="flex flex-row">
                <div className="hidden lg:block w-[18%]">
                  <Sidebar/>
                </div>
                <div className="col-spaan-3 overflow-auto col-span-5 lg:border-l w-[82%]">
                  <div className="px-5 py-6 lg:px-8">
                    <Header/>
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
